### ISSUE TITLE
Boutons pause inopérants (pas encore implémenté)

### ISSUE THREAD

**Issue by arnaud-clere** [Recovid/ihm#2]
Il s'agit à priori d'un requirement critique mais je ne trouve pas de spec.
Le projet MUR spécifie qu'ils mettent en pause seulement lorsqu'ils sont appuyés et que la pause s'interrompt dès que le doigt quitte l'écran.

Autre problème (trivial) :
- [ ] label "inspi" en double > "expi"

**Comment by jeromemaisonnasse** [comment]
On a fait un choix un peu différent. La pause expi/inspi se fait dès que l'on appuie sur le bouton. Lorsque l'on relache, ça active tout de suite le gele des courbes pour vérifier les données. Pour relancer le live, il faut rappuyer sur le gele des courbes. Je sais pas si faut que l'on revoit ce comportement.

**Comment by Shikoruma** [comment]
C'est corrigé
