### ISSUE TITLE
Boutons +/- à améliorer

### ISSUE THREAD

**Issue by arnaud-clere** [Recovid/ihm#3]
Les Knobs ne semblent pas idéaux en interaction tactile (et accessoirement inopérant dans mon environnement et ma version). Je crains qu'il soit compliqué de faire des réglages fins et pas impossible de faire des changements extrêmes non désirés en fonction de la taille de l'écran, de la sensibilité du tactile, du port de gants, etc.

Aussi, il n'est pas évident qu'il faille appuyer au centre pour déverrouiller la consigne. Un design plus simple de boutons affichant la consigne (pour verrouiller/déverrouiller) et de boutons +/- voire ++/+/-/-- en dessous me semble plus simple et plus utilisable.

**Comment by jeromemaisonnasse** [comment]
Ici, on s'appuie sur une interface existant de respi utilisé au CHU. Donc à prioiri, ça doit être bon. Les + et - sont fait avec un encodeur physique et pas d'interaction logiciel.

**Comment by Shikoruma** [comment]
On a changé pour la version bouton dans l'interface
